#|
 | Each new term in the Fibonacci sequence is generated by adding the previous two
 | terms.  By starting with 1 and 2, the first terms will be: 1,2,3,5,...
 | By considering the terms in the fibonacci sequence whose values do not exceed
 | four million, find the sum of the even-valued terms.
 |#

#lang racket

(require math)

(define LIMIT 4000000)

(define (even-valued-terms cur pre out)
  (if (< cur LIMIT)
    (if (even? cur)
      (even-valued-terms (+ cur pre) cur (cons cur out))
      (even-valued-terms (+ cur pre) cur out))
    out))

(sum (even-valued-terms 1 0 '()))
#| 4613732 |#
